mysite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from mysite import settings

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', login_required(views.DetailView.as_view()), name='detail'),
    path('<int:pk>/results/', login_required(views.ResultsView.as_view()), name='results'),
    path('<int:question_id>/vote/', login_required(views.vote), name='vote'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('logout/', login_required(views.LogoutView.as_view()), name='logout'),
    path('profile/', login_required(views.ProfileView.as_view()), name='profile'),
    path('<int:pk>/edit/', login_required(views.EditAccView.as_view()), name='edit'),
    path('<int:pk>/delete/', login_required(views.DeleteAccView.as_view()), name='delete')
]

polls/models.py
import datetime

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone


class SomeUser(AbstractUser):
    img = models.ImageField(null=True, upload_to='static/img/', verbose_name='Изображение')


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    img = models.ImageField(null=True, blank=True, upload_to='static/img/')
    pub_date = models.DateTimeField('date published')
    voted_users = models.ManyToManyField(SomeUser, null=True, blank=True, verbose_name='Проголосовавшие',
                                         related_name='related_user')

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import SomeUser


class RegisterForm(UserCreationForm):
    img = forms.ImageField(required=False, label='Изображение')

    class Meta:
        model = SomeUser
        fields = [
            'username',
            'img'
        ]

polls/views.py
import datetime

from django.contrib.auth import views
from django.contrib.auth.models import User
from django.db.models import Sum
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import CreateView, TemplateView, UpdateView, DeleteView

from .forms import RegisterForm
from .models import Question, Choice, SomeUser
from django.template import loader
from django.urls import reverse, reverse_lazy
from django.views import generic, View


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date').filter(
            pub_date__range=[datetime.datetime.now() - datetime.timedelta(days=30), datetime.datetime.now()]
        )

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['description'] = Question.objects.all().values_list('description')
        return context


class LoginView(views.LoginView):
    template_name = 'polls/login.html'

    def get_redirect_url(self):
        return reverse('polls:index')



class RegisterView(CreateView):
    template_name = 'polls/register.html'
    model = User
    form_class = RegisterForm
    success_url = reverse_lazy('polls:login')


class LogoutView(views.LogoutView):
    template_name = 'polls/logout.html'

    def get_success_url(self):
        return reverse_lazy('polls:index')


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

    def get_context_data(self, **kwargs):

        context = super(ResultsView, self).get_context_data(**kwargs)
        context['votes'] = Choice.objects.all().filter(question_id=self.kwargs['pk']).aggregate(Sum('votes'))
        return context


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': 'вы не сделали выбор'
        })
    else:
        if Question.objects.filter(id=question.id).filter(voted_users=request.user).exists():
            return render(request, 'polls/detail.html', {
                'question': question,
                'error_message': 'вы уже проголосовали'
            })
        else:
            question.voted_users.add(request.user)
            selected_choice.votes += 1
            selected_choice.save()
            return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


class ProfileView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'polls/profile.html')


class EditAccView(UpdateView):
    model = SomeUser
    template_name = 'polls/edit.html'
    fields = (
        'username',
        'img'
    )

    def get_success_url(self):
        return reverse_lazy('polls:profile')


class DeleteAccView(DeleteView):
    model = SomeUser
    template_name = 'polls/delete.html'

    def get_object(self, **kwargs):
        pk = self.kwargs.get(self.pk_url_kwarg)
        user = SomeUser.objects.get(pk=pk)
        return user

    def get_success_url(self):
        return reverse_lazy('polls:profile')

polls/templates/base.html
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery="slim" %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
            integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
            integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
            crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>{% block title %} Title {% endblock %}</title>
</head>
<body>

<div>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand fs-5" href="{% url 'polls:index' %}">Polls</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link fs-5" href="{% url 'polls:index' %}">Главная</a>
        </li>
        <li class="nav-item">
          <a class="nav-link fs-5" href="{% url 'polls:profile' %}">Профиль</a>
        </li>
           {% if user.is_authenticated %}
           <li class="nav-item">
          <a class="nav-link fs-5" href="{% url 'polls:logout' %}">Выйти</a>
        </li>
          {% else %}
          <li class="nav-item">
          <a class="nav-link fs-5" href="{% url 'polls:login' %}">Войти</a>
        </li>
          {% endif %}
          <li class="nav-item">
          <a class="nav-link fs-5" href="{% url 'polls:register' %}">Регистрация</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
</div>
<div class="content container">
    {% block content %}

    {% endblock %}
</div>

</body>
</html>

polls/templates/polls/delete.html
  {% extends 'base.html' %}
{% load templates %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery="slim" %}
{% load static %}

{% block content %}
    <form action="" method="post">{% csrf_token %}
        <div class="card">
  <div class="card-body d-flex flex-column justify-content-center align-items-center">
    <h5 class="card-title text-center">Вы уверены, что хотите удалить аккаунт?</h5>
      <div>
          <input type="submit" class="btn btn-primary" value="Да" />
      </div>

  </div>
</div>

    </form>


  {% endblock %}

polls/templates/polls/detail.html
{% extends 'base.html' %}
{% load templates %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery="slim" %}

{% block content %}


<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
    <div class="card">
    <div class="card-body">
        <h5 class="card-title">{{question.question_text}}</h5>
        <p class="card-text">{{question.description}}</p>
        {% if question.img %}
        <img src="{{ question.img.url }}" alt="question_ img">
        {% endif %}
        {% if error_message %}
        <div class="alert alert-danger" role="alert">
            {{error_message}}
        </div>
        {% endif %}
        {% for choice in question.choice_set.all %}
        <div class="form-check">
            <input class="form-check-input" type="radio" name="choice" id="{{forloop.counter}}" value="{{choice.id}}">
            <label class="form-check-label" for="{{forloop.counter}}">
                {{choice.choice_text}}
            </label>
        </div>
        {% endfor %}
    </div>
    </div>
    </fieldset>

<input class="btn btn-primary" type="submit" value="Проголосовать">

</form>

{% endblock %}

polls/templates/polls/edit.html
{% extends 'base.html' %}
{% load templates %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery="slim" %}
{% load static %}

{% block content %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form layout='vertical' %}
    {% buttons submit='Сохранить' %}
    {% endbuttons %}
</form>
{% endblock %}

polls/templates/polls/index.html
{% extends 'base.html' %}
{% load templates %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery="slim" %}

{% block content %}
{#    {% if latest_question_list %}#}
{#<ul>#}
{#    {% for question in latest_question_list %}#}
{#    <li><a href="{% url 'polls:detail' question.id %}">{{question.question_text}}</a> </li>#}
{#    <p>{% textSlice question.description %}</p>#}
{#    {% endfor %}#}
{#</ul>#}
{#    {% else %}#}
{#     <p>#}
{#         Нет вопросов!#}
{#     </p>#}
{##}
{#{% endif %}#}

    {% for question in latest_question_list %}
    <div class="index card border border-primary">
  <div class="card-body">
    <a href="{% url 'polls:detail' question.id %}" class="card-title text-decoration-none fs-2">{{question.question_text}}</a>
    <p class="card-text">{% textSlice question.description %}</p>
  </div>
</div>
    {% endfor %}
{% endblock %}

polls/templates/polls/login.html
{% extends 'base.html' %}
{% load templates %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery="slim" %}
{% load static %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='vertical' %}
    {% buttons submit='Авторизация' %}
    {% endbuttons %}
</form>
{% endblock %}

polls/templates/polls/logout.html
  {% extends 'base.html' %}
{% load templates %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery="slim" %}
{% load static %}

{% block content %}
          <div class="card">
  <div class="card-body d-flex flex-column justify-content-center align-items-center">
    <h5 class="card-title text-center">Вы успешно вышли с сайта</h5>
      <div>
          <a href="{% url 'polls:index' %}" class="btn btn-primary">Вернуться на главную</a>
      </div>

  </div>
</div>

  {% endblock %}

polls/templates/polls/profile.html
{% extends 'base.html' %}
{% load templates %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery="slim" %}
{% load static %}

{% block content %}
    <div class="card profile border border-primary mb-3">
  <div class="row g-0">
    <div class="col-md-4">
        {% if user.img %}
      <img src="{{ user.img.url }}" alt="profile_ img" class="img-fluid rounded-start">
        {% else %}
        <img src="{% static 'img/img.png' %}" alt="profile_ img" class="img-fluid rounded-start">
    {% endif %}
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h2 class="card-title text-primary">{{ user }}</h2>
        <a href="{% url 'polls:edit' pk=user.id %}" class="card-link"><small>Редактировать</small></a><br>
          <a href="{% url 'polls:delete' user.id %}" class="card-link"><small>Удалить аккаунт</small></a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

polls/templates/polls/register.html
{% extends 'base.html' %}
{% load templates %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery="slim" %}


{% load static %}

{% block content %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form layout='vertical' %}
    {% buttons submit='Регистрация' %}
    {% endbuttons %}
</form>
{% endblock %}

polls/templates/polls/results.html
{% extends 'base.html' %}
{% load templates %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery="slim" %}

{% block content %}
<div class="card">
  <div class="card-body">
    <h5 class="card-title">{{ question.question_text }}</h5>
    <ul class="list-group">
    {% for choice in question.choice_set.all %}
  <li class="list-group-item d-flex justify-content-between align-items-center">
      {{ choice.choice_text }} <span class="badge bg-primary rounded-pill">{% percent choice.votes votes.votes__sum %}%</span>
  </li>
    {% endfor %}
</ul>
    <a href="{% url 'polls:index' %}" class="card-link">Вернуться на главную</a>
  </div>
</div>
{% endblock %}